name: Deploy to GitHub Pages

on:
  # 触发条件
  push:
    branches: [main]
  pull_request:
    branches: [main] # 在PR时也运行可以提前发现问题
  workflow_dispatch: # 允许手动触发

# 设置并行任务数，避免运行太多实例
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # 如果有新的提交，取消正在运行的工作流

# 权限设置（最小化所需权限）
permissions:
  contents: read
  pages: write
  id-token: write # 需要部署到 GitHub Pages 的 ID 令牌

# 环境变量
env:
  NODE_VERSION: 20 # Node.js 版本
  YARN_VERSION: 1.22.19 # 使用yarn
  BUILD_PATH: "dist" # Astro 默认输出目录

jobs:
  build:
    name: 构建网站
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的git历史用于更好的缓存

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn" # 使用内置的yarn缓存

      - name: Get Yarn cache directory
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Setup Yarn cache
        uses: actions/cache@v4 # 更新到最新版本
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile # 确保依赖锁定

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps chromium

      # 添加缓存（可选但推荐）
      - name: Cache Playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Build site
        run: |
          echo "Starting build..."
          yarn build
          echo "Build completed successfully."

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}

  deploy:
    name: 部署到GitHub Pages
    if: github.event_name != 'pull_request' # 只在非PR事件中部署
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000 # 设置更长的超时时间（毫秒）
